apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podsecretdemos.rudrakhp.com
spec:
  group: rudrakhp.com
  names:
    kind: PodSecretDemo
    listKind: PodSecretDemoList
    plural: podsecretdemos
    singular: podsecretdemo
    shortNames:
      - psd
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secret:
                  type: string
                data:
                  type: string
                opt:
                  type: string
              required:
                - secret
                - data