# permissions for end users to view podsecretdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podsecretdemo-viewer-role
rules:
- apiGroups:
  - demo.rudrakhp.com
  resources:
  - podsecretdemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.rudrakhp.com
  resources:
  - podsecretdemoes/status
  verbs:
  - get
