# permissions for end users to edit podsecretdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podsecretdemo-editor-role
rules:
- apiGroups:
  - demo.rudrakhp.com
  resources:
  - podsecretdemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.rudrakhp.com
  resources:
  - podsecretdemoes/status
  verbs:
  - get
