---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - demo.rudrakhp.com
  resources:
  - podsecretdemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.rudrakhp.com
  resources:
  - podsecretdemoes/finalizers
  verbs:
  - update
- apiGroups:
  - demo.rudrakhp.com
  resources:
  - podsecretdemoes/status
  verbs:
  - get
  - patch
  - update
